### GET request to example server
GET http://localhost:8080/api/v2/notes

### Sign user up
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "test2@email.com",
  "username": "heem",
  "password": "spence",
  "confirmPassword": "spence"
}

### Log user in
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test2@email.com",
  "password": "spence"
}

### Get all course specific note for logged in user
GET http://localhost:8080/courses/1/notes

### Create note for logged in user for specific course
POST http://localhost:8080/courses/1/notes
Content-Type: application/json

{
  "title": "Test note 3",
  "content": "Testing updating note with course membership in mind"
}

### Update note for logged in user
PUT http://localhost:8080/courses/1/notes/10
Content-Type: application/json

{
  "title": "Update test 3",
  "content": "Testing updated note functionality with course membership in mind"
}

### Delete note for logged in user for specific course
DELETE http://localhost:8080/courses/1/notes/9

### Create course for logged in user
POST http://localhost:8080/course/create
Content-Type: application/json

{
  "className": "Chemistry",
  "school": "Bates College",
  "joinCode": "321"
}

### Join class for logged in user
POST http://localhost:8080/course/join
Content-Type: application/json

{
  "courseName": "Chemistry",
  "joinCode": "321"
}