spring.application.name=notes-api-v2
spring.datasource.url=jdbc:postgresql://localhost:5333/noteshare
spring.datasource.username=raheemspence
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
